export const STOCKHOLM_TIME_ZONE = "Europe/Stockholm";

export const PILOT_STATIONS = [
  {
    externalId: "SE_STA_LKP",
    name: "Linköping C",
    municipality: "Linköping",
    latitude: 58.4165,
    longitude: 15.6254,
  },
  {
    externalId: "SE_STA_NRK",
    name: "Norrköping C",
    municipality: "Norrköping",
    latitude: 58.5962,
    longitude: 16.1836,
  },
  {
    externalId: "SE_STA_MJO",
    name: "Mjölby",
    municipality: "Mjölby",
    latitude: 58.3227,
    longitude: 15.1315,
  },
  {
    externalId: "SE_STA_STO",
    name: "Stockholm Central",
    municipality: "Stockholm",
    latitude: 59.3299708,
    longitude: 18.057267,
  },
  {
    externalId: "SE_STA_SOD",
    name: "Södertälje Syd",
    municipality: "Södertälje",
    latitude: 59.1632977,
    longitude: 17.6479617,
  },
  {
    externalId: "SE_STA_KAT",
    name: "Katrineholm C",
    municipality: "Katrineholm",
    latitude: 58.9965117,
    longitude: 16.2091836,
  },
  {
    externalId: "SE_STA_UPP",
    name: "Uppsala C",
    municipality: "Uppsala",
    latitude: 59.8578817,
    longitude: 17.6486938,
  },
  {
    externalId: "SE_STA_GAV",
    name: "Gävle C",
    municipality: "Gävle",
    latitude: 60.6760861,
    longitude: 17.15175,
  },
  {
    externalId: "SE_STA_SUN",
    name: "Sundsvall C",
    municipality: "Sundsvall",
    latitude: 62.3865742,
    longitude: 17.3148893,
  },
  {
    externalId: "SE_STA_VAS",
    name: "Västerås C",
    municipality: "Västerås",
    latitude: 59.6076959,
    longitude: 16.5529114,
  },
  {
    externalId: "SE_STA_ESK",
    name: "Eskilstuna C",
    municipality: "Eskilstuna",
    latitude: 59.3693876,
    longitude: 16.5054559,
  },
  {
    externalId: "SE_STA_ORE",
    name: "Örebro C",
    municipality: "Örebro",
    latitude: 59.278214,
    longitude: 15.2109563,
  },
  {
    externalId: "SE_STA_JON",
    name: "Jönköping C",
    municipality: "Jönköping",
    latitude: 57.7844577,
    longitude: 14.1645738,
  },
  {
    externalId: "SE_STA_NAS",
    name: "Nässjö C",
    municipality: "Nässjö",
    latitude: 57.6513594,
    longitude: 14.6947346,
  },
  {
    externalId: "SE_STA_GOT",
    name: "Göteborg C",
    municipality: "Göteborg",
    latitude: 57.7089008,
    longitude: 11.9738943,
  },
  {
    externalId: "SE_STA_ALV",
    name: "Alvesta",
    municipality: "Alvesta",
    latitude: 56.8980219,
    longitude: 14.5561918,
  },
  {
    externalId: "SE_STA_LUN",
    name: "Lund C",
    municipality: "Lund",
    latitude: 55.7072496,
    longitude: 13.1865727,
  },
  {
    externalId: "SE_STA_MAL",
    name: "Malmö C",
    municipality: "Malmö",
    latitude: 55.6097182,
    longitude: 13.0002298,
  },
] as const;

export interface MockJourneyTemplate {
  externalJourneyId: string;
  originExternalId: string;
  destinationExternalId: string;
  departureTime: string;
  durationMinutes: number;
  transferCount: number;
  routeDescription: string;
  operatorName: string;
  serviceCategory: "local" | "regional" | "intercity" | "mixed";
  baseDelayMinutes: number;
  cancellationEvery: number;
  majorDelayEvery: number;
  missingEvery: number;
  transferMissEvery?: number;
}

export const PILOT_STATION_PROVIDER_IDS: Record<
  (typeof PILOT_STATIONS)[number]["externalId"],
  { trafikverketLocationSignature: string }
> = {
  SE_STA_LKP: { trafikverketLocationSignature: "Lp" },
  SE_STA_NRK: { trafikverketLocationSignature: "Nr" },
  SE_STA_MJO: { trafikverketLocationSignature: "My" },
  SE_STA_STO: { trafikverketLocationSignature: "Cst" },
  SE_STA_SOD: { trafikverketLocationSignature: "Söö" },
  SE_STA_KAT: { trafikverketLocationSignature: "K" },
  SE_STA_UPP: { trafikverketLocationSignature: "U" },
  SE_STA_GAV: { trafikverketLocationSignature: "Gä" },
  SE_STA_SUN: { trafikverketLocationSignature: "Suc" },
  SE_STA_VAS: { trafikverketLocationSignature: "Vå" },
  SE_STA_ESK: { trafikverketLocationSignature: "Et" },
  SE_STA_ORE: { trafikverketLocationSignature: "Ör" },
  SE_STA_JON: { trafikverketLocationSignature: "Jö" },
  SE_STA_NAS: { trafikverketLocationSignature: "N" },
  SE_STA_GOT: { trafikverketLocationSignature: "G" },
  SE_STA_ALV: { trafikverketLocationSignature: "Av" },
  SE_STA_LUN: { trafikverketLocationSignature: "Lu" },
  SE_STA_MAL: { trafikverketLocationSignature: "Mc" },
};

export const MOCK_JOURNEY_TEMPLATES: readonly MockJourneyTemplate[] = [
  {
    externalJourneyId: "mock-lkp-nrk-0645",
    originExternalId: "SE_STA_LKP",
    destinationExternalId: "SE_STA_NRK",
    departureTime: "06:45",
    durationMinutes: 27,
    transferCount: 0,
    routeDescription: "Östgötapendeln direkt",
    operatorName: "Östgötatrafiken",
    serviceCategory: "local",
    baseDelayMinutes: 1,
    cancellationEvery: 67,
    majorDelayEvery: 23,
    missingEvery: 41,
  },
  {
    externalJourneyId: "mock-lkp-nrk-0715",
    originExternalId: "SE_STA_LKP",
    destinationExternalId: "SE_STA_NRK",
    departureTime: "07:15",
    durationMinutes: 27,
    transferCount: 0,
    routeDescription: "Östgötapendeln direkt",
    operatorName: "Östgötatrafiken",
    serviceCategory: "local",
    baseDelayMinutes: 2,
    cancellationEvery: 43,
    majorDelayEvery: 17,
    missingEvery: 37,
  },
  {
    externalJourneyId: "mock-lkp-nrk-0745",
    originExternalId: "SE_STA_LKP",
    destinationExternalId: "SE_STA_NRK",
    departureTime: "07:45",
    durationMinutes: 27,
    transferCount: 0,
    routeDescription: "Östgötapendeln direkt",
    operatorName: "Östgötatrafiken",
    serviceCategory: "local",
    baseDelayMinutes: 3,
    cancellationEvery: 31,
    majorDelayEvery: 13,
    missingEvery: 29,
  },
  {
    externalJourneyId: "mock-lkp-sto-0542",
    originExternalId: "SE_STA_LKP",
    destinationExternalId: "SE_STA_STO",
    departureTime: "05:42",
    durationMinutes: 113,
    transferCount: 0,
    routeDescription: "SJ snabbtåg direkt",
    operatorName: "SJ",
    serviceCategory: "intercity",
    baseDelayMinutes: 1,
    cancellationEvery: 71,
    majorDelayEvery: 29,
    missingEvery: 43,
  },
  {
    externalJourneyId: "mock-lkp-sto-0618",
    originExternalId: "SE_STA_LKP",
    destinationExternalId: "SE_STA_STO",
    departureTime: "06:18",
    durationMinutes: 112,
    transferCount: 0,
    routeDescription: "SJ snabbtåg direkt",
    operatorName: "SJ",
    serviceCategory: "intercity",
    baseDelayMinutes: 2,
    cancellationEvery: 61,
    majorDelayEvery: 23,
    missingEvery: 47,
  },
  {
    externalJourneyId: "mock-lkp-sto-0648",
    originExternalId: "SE_STA_LKP",
    destinationExternalId: "SE_STA_STO",
    departureTime: "06:48",
    durationMinutes: 116,
    transferCount: 1,
    routeDescription: "Östgötapendeln, byte i Norrköping till Mälartåg",
    operatorName: "Östgötatrafiken + Mälartåg",
    serviceCategory: "mixed",
    baseDelayMinutes: 5,
    cancellationEvery: 29,
    majorDelayEvery: 11,
    missingEvery: 31,
    transferMissEvery: 9,
  },
  {
    externalJourneyId: "mock-lkp-sto-0718",
    originExternalId: "SE_STA_LKP",
    destinationExternalId: "SE_STA_STO",
    departureTime: "07:18",
    durationMinutes: 112,
    transferCount: 0,
    routeDescription: "SJ snabbtåg direkt",
    operatorName: "SJ",
    serviceCategory: "intercity",
    baseDelayMinutes: 4,
    cancellationEvery: 37,
    majorDelayEvery: 13,
    missingEvery: 41,
  },
  {
    externalJourneyId: "mock-lkp-sto-0748",
    originExternalId: "SE_STA_LKP",
    destinationExternalId: "SE_STA_STO",
    departureTime: "07:48",
    durationMinutes: 117,
    transferCount: 1,
    routeDescription: "Östgötapendeln, byte i Norrköping till Mälartåg",
    operatorName: "Östgötatrafiken + Mälartåg",
    serviceCategory: "mixed",
    baseDelayMinutes: 6,
    cancellationEvery: 23,
    majorDelayEvery: 9,
    missingEvery: 31,
    transferMissEvery: 7,
  },
  {
    externalJourneyId: "mock-nrk-sto-0617",
    originExternalId: "SE_STA_NRK",
    destinationExternalId: "SE_STA_STO",
    departureTime: "06:17",
    durationMinutes: 82,
    transferCount: 0,
    routeDescription: "Mälartåg direkt",
    operatorName: "Mälartåg",
    serviceCategory: "regional",
    baseDelayMinutes: 1,
    cancellationEvery: 67,
    majorDelayEvery: 27,
    missingEvery: 43,
  },
  {
    externalJourneyId: "mock-nrk-sto-0647",
    originExternalId: "SE_STA_NRK",
    destinationExternalId: "SE_STA_STO",
    departureTime: "06:47",
    durationMinutes: 81,
    transferCount: 0,
    routeDescription: "Mälartåg direkt",
    operatorName: "Mälartåg",
    serviceCategory: "regional",
    baseDelayMinutes: 2,
    cancellationEvery: 47,
    majorDelayEvery: 19,
    missingEvery: 37,
  },
  {
    externalJourneyId: "mock-nrk-sto-0717",
    originExternalId: "SE_STA_NRK",
    destinationExternalId: "SE_STA_STO",
    departureTime: "07:17",
    durationMinutes: 82,
    transferCount: 0,
    routeDescription: "Mälartåg direkt",
    operatorName: "Mälartåg",
    serviceCategory: "regional",
    baseDelayMinutes: 4,
    cancellationEvery: 31,
    majorDelayEvery: 13,
    missingEvery: 29,
  },
  {
    externalJourneyId: "mock-mjo-lkp-0624",
    originExternalId: "SE_STA_MJO",
    destinationExternalId: "SE_STA_LKP",
    departureTime: "06:24",
    durationMinutes: 24,
    transferCount: 0,
    routeDescription: "Östgötapendeln direkt",
    operatorName: "Östgötatrafiken",
    serviceCategory: "local",
    baseDelayMinutes: 1,
    cancellationEvery: 59,
    majorDelayEvery: 23,
    missingEvery: 47,
  },
  {
    externalJourneyId: "mock-mjo-sto-0549",
    originExternalId: "SE_STA_MJO",
    destinationExternalId: "SE_STA_STO",
    departureTime: "05:49",
    durationMinutes: 148,
    transferCount: 1,
    routeDescription: "Östgötapendeln, byte i Linköping till SJ snabbtåg",
    operatorName: "Östgötatrafiken + SJ",
    serviceCategory: "mixed",
    baseDelayMinutes: 4,
    cancellationEvery: 37,
    majorDelayEvery: 15,
    missingEvery: 31,
    transferMissEvery: 11,
  },
  {
    externalJourneyId: "mock-mjo-sto-0619",
    originExternalId: "SE_STA_MJO",
    destinationExternalId: "SE_STA_STO",
    departureTime: "06:19",
    durationMinutes: 151,
    transferCount: 1,
    routeDescription: "Östgötapendeln, byte i Linköping till SJ snabbtåg",
    operatorName: "Östgötatrafiken + SJ",
    serviceCategory: "mixed",
    baseDelayMinutes: 6,
    cancellationEvery: 29,
    majorDelayEvery: 11,
    missingEvery: 29,
    transferMissEvery: 8,
  },
] as const;
